name: Build PR

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup Elm
        uses: justgook/setup-elm@v1
        
      - name: Build exercise
        run: elm make src/*.elm
      - name: Upload exercise
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Web page
          path: index.html
